### ISSUE TITLE
scope: c++

### ISSUE THREAD

**Issue by ssj71** [puglfork/pugl#5]
I know this is just asking for a battle in the holy war, but we have some forks that are using obj-c++/c++ for the backend implementation. It seems there isn't interest in moving the X11 implementation to c++ but the current windows backend is already .cpp and the dpf fork is now using a obj-c++ for macos. That specifically relates to their use of cairo (see #1 ).

I personally prefer C but are there objective arguments for either case?

I suspect this is an instance where the benevolent dictatorship model has distinct advantages over democracy.

**Comment by jpcima** [comment]
I don't find many reasons that would justify a switch to C++ in pugl.

>the dpf fork is now using a obj-c++ for macos

The mac OS part of DPF does not, at present state, require Obj-C++.

Let me clarify: according to falktx, a language change will permit to eliminate a redundancy, applying a hypothetical solution based on templates.
Myself, I don't believe such a solution to be possible, but I wait to see.

>the current windows backend is already .cpp

Possibly, to deal with MS compiler and its extravagances. It's a wild guess.
The code is a trivial conversion to C under Gcc.

**Comment by drobilla** [comment]
> Possibly, to deal with MS compiler and its extravagances. It's a wild guess.
> The code is a trivial conversion to C under Gcc.

It was always "mostly C", except for a very recent blip, but the Windows backend upstream is now literally C (e7d9aaf) and there are CI rows to build it with MinGW GCC.  The build system does build it as C++ on MSVC, though, because this is the only way to build modern C with that compiler.

Using C++ in general is a bad idea, it introduces a bunch of binary compatibility problems, but this isn't really much of a problem on Windows and MacOS where the platform is uniform anyway.
